# Generated by Django 3.2 on 2021-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(unique=True)),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
